# ===============================================
# [네임스페이스 → data-layer]
# ===============================================
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/part-of: data-layer