# ===============================================
# [Prometheus Deployment ingress]
# → 외부에서 Prometheus UI에 접근하기 위한 진입점
# → Host 기준으로 Prometheus Service에 연결
# ===============================================
apiVersion: networking.k8s.io/v1
kind: Ingress # 쿠버네티스 인그레스 리소스
metadata:
  name: prometheus
  namespace: {{ .Values.global.namespace }}
  labels:
    app: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: data-layer
spec:
  ingressClassName: {{ .Values.global.ingressClassName }} # 사용할 Ingress Controller
  rules:
    - host: {{ .Values.global.hosts.prometheus }} # 요청 Host → Prometheus로 라우팅
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: # 요청을 전달할 Service
                name: prometheus
                port:
                  number: {{ .Values.prometheus.port }} # Service 포트